version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/StoreFeatured
    steps:
      - checkout
      - run: npm install
      - run: npm test